version: '3.8'
services:
  postgres-test:
    image: postgres:15
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: gestion_peliculas_test
    ports:
      - '5433:5432'
